export {
  getAllPostsId,
  getMainPostsAPI,
  getAllCategoryLengthAPI,
  getPostAPI,
  getCategoryPostAPI,
  getSearchPostAPI,
  getTagPostAPI,
  AddPostAPI,
  EditPostAPI,
  DeletePostAPI,
  getPostViewCountAPI,
  GetTopViewsPostsAPI,
  getSeriesPostAPI,
} from "./post.service";
