export {
  getAllPostsId,
  getMainPostsAPI,
  getAllCategoryLengthAPI,
  getOnePostAPI,
  getCategoryPostAPI,
  getSearchPostAPI,
  getTagPostAPI,
  AddPostAPI,
  EditPostAPI,
  DeletePostAPI,
  getCommentAPI,
  getPostViewCountAPI,
  AddCommentAPI,
  GetTopViewsPostsAPI,
} from "./post.service";
